title: Settings
modelClass: Undirezt\Telegramfeedback\Models\Settings
list: $/undirezt/telegramfeedback/models/settings/columns.yaml
recordUrl: 'undirezt/telegramfeedback/settings/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '20'
showSetup: 1
showCheckboxes: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
